import { LogResult } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import crypto from "crypto";
import { requireSuperAdminApi } from "@/lib/auth/api-access";
import { affiliateAdminSchema } from "@/lib/admin/schemas";
import { db } from "@/lib/db";
import { writeAuditLog } from "@/lib/logging/audit";
import { encryptValue } from "@/lib/security/encryption";

const affiliateUpdateSchema = affiliateAdminSchema.extend({
  id: z.string(),
  isActive: z.boolean(),
});

function generateSecret(): string {
  return crypto.randomBytes(32).toString("hex");
}

export async function POST(request: Request) {
  const auth = await requireSuperAdminApi();

  if (!auth.ok) {
    return auth.response;
  }

  const body = await request.json();
  const parsed = affiliateAdminSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, message: "参数不合法", issues: parsed.error.flatten() },
      { status: 400 },
    );
  }

  const intakeSecret = parsed.data.intakeSecret?.trim() || generateSecret();
  const callbackSecret = parsed.data.callbackSecret?.trim() || generateSecret();

  const affiliate = await db.affiliate.create({
    data: {
      code: parsed.data.code,
      name: parsed.data.name,
      intakeSecretEncrypted: intakeSecret ? encryptValue(intakeSecret) : null,
      callbackSecretEncrypted: callbackSecret ? encryptValue(callbackSecret) : null,
    },
  });

  await writeAuditLog({
    actorId: auth.session.sub,
    eventType: "admin.affiliate_created",
    result: LogResult.SUCCESS,
    targetType: "affiliate",
    targetId: affiliate.id,
    metadata: {
      code: parsed.data.code,
      name: parsed.data.name,
      intakeSecretAutoGenerated: !!intakeSecret,
      callbackSecretAutoGenerated: !!callbackSecret,
    },
  });

  return NextResponse.json({
    ok: true,
    affiliate: {
      id: affiliate.id,
      code: affiliate.code,
      name: affiliate.name,
      intakeSecret: intakeSecret || null,
      callbackSecret: callbackSecret || null,
    },
  });
}

export async function PATCH(request: Request) {
  const auth = await requireSuperAdminApi();

  if (!auth.ok) {
    return auth.response;
  }

  const body = await request.json();
  const parsed = affiliateUpdateSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, message: "参数不合法", issues: parsed.error.flatten() },
      { status: 400 },
    );
  }

  const updateData: {
    name?: string;
    code?: string;
    isActive?: boolean;
    intakeSecretEncrypted?: string;
    callbackSecretEncrypted?: string;
  } = {
    name: parsed.data.name,
    code: parsed.data.code,
    isActive: parsed.data.isActive,
  };

  if (parsed.data.intakeSecret) {
    updateData.intakeSecretEncrypted = encryptValue(parsed.data.intakeSecret);
  }
  if (parsed.data.callbackSecret) {
    updateData.callbackSecretEncrypted = encryptValue(parsed.data.callbackSecret);
  }

  const affiliate = await db.affiliate.update({
    where: { id: parsed.data.id },
    data: updateData,
  });

  await writeAuditLog({
    actorId: auth.session.sub,
    eventType: "admin.affiliate_updated",
    result: LogResult.SUCCESS,
    targetType: "affiliate",
    targetId: affiliate.id,
    metadata: {
      code: affiliate.code,
      name: affiliate.name,
      isActive: parsed.data.isActive,
      intakeSecretUpdated: !!parsed.data.intakeSecret,
      callbackSecretUpdated: !!parsed.data.callbackSecret,
    },
  });

  return NextResponse.json({ ok: true, affiliate });
}
